### PR TITLE
Add new station in France

### PR DESCRIPTION
**Pull request by thibautrey**

### CODE REVIEW

**Comment by rdz-oss** [comment]
Great! I will check and see if I can add some of the false detections in your surroundings to the noise training set!

**Comment by thibautrey** [comment]
Yes that would be awesome. I've got quite a lot of false detections of species that simply can't exist in france. 
I'm not quite sure why they are detected in the first place. 

I have set BirdNET_GLOBAL_6K_V2.4_Model_FP16
With a Species Occurence Frequency Threshold of 0,7

Also the species list tester returns an error when testing on the GUI

`Fatal error:  Uncaught ValueError: shell_exec(): Argument #1 ($command) cannot be empty in /home/thibautrey/BirdNET-Pi/scripts/config.php:57
Stack trace:
#0 /home/thibautrey/BirdNET-Pi/scripts/config.php(57): shell_exec()
#1 {main}
  thrown in /home/thibautrey/BirdNET-Pi/scripts/config.php on line 57
`

**Comment by stewartwlewis** [comment]
I am having the same problem with all sorts of birds and bats being identified that don't exist where I am in the UK.  I get the error when using either the image build or using a vanilla raspian build and  github download.  

In the overview page I also get the following two errors.

Fatal error: Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, bool given in /home/pi/BirdNET-Pi/scripts/overview.php:161 Stack trace: #0 /home/pi/BirdNET-Pi/scripts/overview.php(161): array_map() #1 {main} thrown in /home/pi/BirdNET-Pi/scripts/overview.php on line 161

and


Fatal error: Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, bool given in /home/pi/BirdNET-Pi/scripts/todays_detections.php:288 Stack trace: #0 /home/pi/BirdNET-Pi/scripts/todays_detections.php(288): array_map() #1 {main} thrown in /home/pi/BirdNET-Pi/scripts/todays_detections.php on line 288

**Comment by EvaldoOliveira** [comment]
Hi,

I have also got this error. 
Solution was to create an empty blackist file.
I guess this is being deleted when you do a clean all in the database

**Comment by rdz-oss** [comment]
Hi @stewartwlewis ,

for birds the exclusion list mechanism is active, i.e. you can reduce the false detections by using the blocked species list.
For bats in the UK, there are two classifiers that should not have non UK species - UK and South-Wales by @Pete-the-Geek . Also, if it is a strong issue for you, you can use the data from the analyzer and make your own classifier with only the species you are interested in  :)
Perhaps you can reduce the number at least for the birds using the Tools- Excluded Species List. That is rather straight-forward. Hope this helps,

BR
Richard

**Comment by stewartwlewis** [comment]
> Hi,
> 
> I have also got this error. Solution was to create an empty blackist file. I guess this is being deleted when you do a clean all in the database

Thanks, that works fine.  
I presume the file add back needs to be in "clear_all_data.sh", had a look and my Unix knowledge isn't up to it and I will stick to your "manual" solution!

**Comment by stewartwlewis** [comment]
Thanks Richard
I have had Birdnet-pi deployed successfully for a while and also a version that I put in the local woods.  The thought of that version being able to do the bird identification and the same for bats is very appealing, but I am having trouble getting sensible values from the new combination of BattyBirdNet and AudioMoth USB. It seems like it's going to be difficult to get good bird identification from AudiMoth and the current spell of gale force winds are making sensible bat testing impossible. 
I will use all of your suggestions thanks and keep at it!

**Comment by Pete-the-Geek** [comment]
> Solution was to create an empty blackist file. I guess this is being deleted when you do a clean all in the database

Ah sorry... I forgot this. I had to do the same. The command was something like :-
touch ~/BirdNET-Pi/exclude_species_list.txt

**Pull request merged**
